### ISSUE TITLE
About the version of pymeshlab

### ISSUE THREAD

**Issue by IridescentJiang** [River-Zhang/GTA#10]
During inferencing, I first installed the current pymeshlab version of 2023.12 and encountered the 
`AttributeError: 'pymeshlab.pmeshlab.MeshSet' object has no attribute 'laplacian_smooth'`

Then I changed the pymeshlab to 2022 and finished the inference successfully.
Maybe the new version of pymeshlab is mismatched with the code.

**Comment by River-Zhang** [comment]
Yes, we used a version of pymeshlab==2022.2.post4. And higher version will cause runtime error. I will update a more detailed instruction about installing the environment. Thanks very much!

**Comment by River-Zhang** [comment]
I have updated the README.md for a detailed installation instruction. Thanks very much!
