### ISSUE TITLE
about SMPLX model

### ISSUE THREAD

**Issue by Followmeczx** [River-Zhang/GTA#13]
In which part of your code do you use a Pixie-like model to estimate SMPLX parameters? I have read your code, and it seems that in the training process, you used the SMPLX parameters obtained from the THuman2.0 dataset as the prior enhancement query. Only when infer was an image, since it was not the image of the dataset, PIXIE model was used to predict the SMPLX parameters as the prior enhancement query. Is my understanding correct?

**Comment by River-Zhang** [comment]
Yes, you are right. During training, we use the GT SMPL-S in the dataset. Only in the inference stage do we use pymaf or pixie to estimate a SMPL or SMPL-X. This is also adopted by PaMIR, ICON and D-IF.
