### ISSUE TITLE
Question about evaluation.

### ISSUE THREAD

**Issue by wszswppx** [River-Zhang/GTA#20]
Hi, thanks for your work.

I noticed you used GT normals while testing on THuman2.0 for normal evaluation of different views (as Table 2 in the paper). I wonder if you are using GT normals too or only GT SMPL-X while testing on CAPE (as in Table 1)? 

![image](https://github.com/River-Zhang/GTA/assets/32038518/78db716a-809d-4364-833a-a86437c81029)

![image](https://github.com/River-Zhang/GTA/assets/32038518/b73ab470-df21-40c9-a9b1-08a008837593)

**Comment by River-Zhang** [comment]
Yes, we also use GT normals, the same as THuman2.0.

**Comment by wszswppx** [comment]
> Yes, we also use GT normals, the same as THuman2.0.

Thanks a lot!
