### ISSUE TITLE
Texture is vertex coloring or PNG ?

### ISSUE THREAD

**Issue by TharHtetAungg** [River-Zhang/GTA#4]
Hi, Can I know about the texture is using vertex coloring or exporting the png format texture?

Thank you.

**Comment by River-Zhang** [comment]
We use vertex coloring in our method. Specifically, we use an MLP to predict the color of each vertex on the mesh. If you need the png format texture map, you can refer to codes from dreamgaussian repository to transfer the vertex color into the texture map.

**Comment by TharHtetAungg** [comment]
@River-Zhang  Could you please show me which part of dreamgaussian code do to transfer the vertex color into the texture map?

**Comment by River-Zhang** [comment]
This can be done with functions from [mesh.py, mesh_renderer.py, and main.py], but you need to change the code slightly. We have implemented a simple script to generate a texture map from vertex-colored mesh, and if you need we can email you. Besides, you could browse GitHub for related repositories, there should be similar projects.

**Comment by TharHtetAungg** [comment]
@River-Zhang Thank you for your information. Could you please share the script with me via my email?

**Comment by River-Zhang** [comment]
we have sent it to you

**Comment by glorioushonor** [comment]
Hi @River-Zhang @TharHtetAungg ,

I’m struggling with this as well. Could you please share the script for generating a texture map from a vertex-colored mesh with me via email? My address is lin_jie@tju.edu.cn.

Thank you!
