### ISSUE TITLE
The test results seems to be inconsistent with the paper

### ISSUE THREAD

**Issue by runningpp** [River-Zhang/GTA#7]
I tried your code in Ubuntu20.04 cuda 11.8 pytorch2.0.1
I have got the results:

https://github.com/River-Zhang/GTA/assets/37203710/9cb33878-6a36-4d85-83d0-61d75fb92086

but the corresponding results in your paper is much better obviously, as shown in the following：
![GTA](https://github.com/River-Zhang/GTA/assets/37203710/46687c98-1053-4b1b-9675-cbd090bfe6bd)

I want to know if my result is reasonable。

**Comment by River-Zhang** [comment]
Thanks for your feedback! That's weird. Here are our results showing in Meshlab:
<img width="1270" alt="image1" src="https://github.com/River-Zhang/GTA/assets/60051616/f862a96c-5864-4f97-b997-4fe34a3bdaed">
<img width="1272" alt="image2" src="https://github.com/River-Zhang/GTA/assets/60051616/5c34b46b-0e63-4610-b6b8-1aa8896ccecb">

Could you kindly display the command you executed along with the output produced by the code? Additionally, I would appreciate it if you could execute the testing script. This will allow me to ascertain whether the test results on CAPE are within expectation.

The only explanation I can think of currently is that there are discrepancies between our environments. We didn't adopt PyTorch versions beyond 2.0 due to compatibility issues with certain features.

**Comment by runningpp** [comment]
> Thanks for your feedback! That's weird. Here are our results showing in Meshlab: <img alt="image1" width="1270" src="https://private-user-images.githubusercontent.com/60051616/295456075-f862a96c-5864-4f97-b997-4fe34a3bdaed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTkzMjksIm5iZiI6MTcwNTI5OTAyOSwicGF0aCI6Ii82MDA1MTYxNi8yOTU0NTYwNzUtZjg2MmE5NmMtNTg2NC00Zjk3LWI5OTctNGZlMzRhM2JkYWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA2MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZWJlNmU0YTE2M2E2OTc3ZTM0OGRmMjhhY2QzMGVmNTAyYTQ0OWJmNDcxYzUzZWJjMGI0M2E3ZmYxNDc3YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2aEOV7jJVcpoZBSDotXF8W9E-PW4YIPi2gl2S5rKYbM"> <img alt="image2" width="1272" src="https://private-user-images.githubusercontent.com/60051616/295456096-5c34b46b-0e63-4610-b6b8-1aa8896ccecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyOTkzMjksIm5iZiI6MTcwNTI5OTAyOSwicGF0aCI6Ii82MDA1MTYxNi8yOTU0NTYwOTYtNWMzNGI0NmItMGU2My00NjEwLWI2YjgtMWFhODg5NmNjZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA2MTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZTFiODVjMGRkMTRiMDlhMDIyZTNkMDI0MGI3YjViNDE4ODY3ZDhhODRjNzk2ZWVkMmRkZTAzNWNmOGJhNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmsi2wefjQcN4sgVwea4Ama4pkpssPp68LDgdXGZ-tE">
> 
> Could you kindly display the command you executed along with the output produced by the code? Additionally, I would appreciate it if you could execute the testing script. This will allow me to ascertain whether the test results on CAPE are within expectation.
> 
> The only explanation I can think of currently is that there are discrepancies between our environments. We didn't adopt PyTorch versions beyond 2.0 due to compatibility issues with certain features.

The command I used:
''
python -m apps.infer -cfg ./configs/GTA.yaml -gpu 0 -in_dir ./examples -out_dir ./results -loop_smpl 100 -loop_cloth 200 -hps_type pixie
"
Note that: I change the GTA.yaml: normal_path: "./data/ckpt/normal.ckpt"  to "./data/ckpt/Normal-epoch=19-v5.ckpt", because the normal mode you provided in [CKPT](https://drive.google.com/file/d/1zgpW8A0-sc24o-e24RphO-h9qxo-DRth/view?usp=sharing) is Normal-epoch=19-v5.ckpt.

The test results in CAPE are:

{'cape-easy-NC': 0.03472820296883583,
 'cape-easy-chamfer': 0.6505321264266968,
 'cape-easy-p2s': 0.6074833273887634,
 'cape-hard-NC': 0.04288707673549652,
 'cape-hard-chamfer': 0.9164005517959595,
 'cape-hard-p2s': 0.8493930101394653}

The I change the the environments to " cuda11.6 pytorch1.13.0", I found the results between the two environments are almost the same. The following is the results on pyotorch 1.13.0:
{'cape-easy-NC': 0.03472774103283882,
 'cape-easy-chamfer': 0.6541368961334229,
 'cape-easy-p2s': 0.6101600527763367,
 'cape-hard-NC': 0.04288462921977043,
 'cape-hard-chamfer': 0.9143836498260498,
 'cape-hard-p2s': 0.8439348340034485}

Maybe it is not caused by the environments. The results you showed have much better detailed surface, can you tell me how to get your shown results?
