### ISSUE TITLE
THuman 2.0 evaluation protocol

### ISSUE THREAD

**Issue by ZZWENG** [River-Zhang/GTA#8]
Hi authors, I have a question regarding the THuman 2.0 evaluation protocol in your Table 1. 

- How do you create train/test split? 
- For the test set, how many views do you render per subject, and what is the FOV?

Thank you in advance!

**Comment by River-Zhang** [comment]
Thank you for your interest in our work. For our test set, we utilize scans numbered from 506 to 526, a total of 21 scans, from the THuman2.0 dataset, as detailed in Section 4 of our paper. The THuman2.0 dataset is preprocessed using the script provided by ICON. In our testing phase, for each scan, we select three different views — 0, 120, and 240 degrees — as inputs. We then reconstruct the mesh for each input view and render normal images from four different angles: 0, 90, 180, and 270 degrees, to evaluate the Normal Consistency (NC) value. During the rendering process, we employ a weak perspective camera model, which places the camera at an extremely far distance, ensuring that the rays are parallel. For more detailed information, please refer to the data processing script (you can find that in ICON's repository).

**Comment by ZZWENG** [comment]
Thank you for your quick response!
